'use client'

import { ArrowDown, ArrowUp, ImagePlus, LoaderCircle } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import { useActionState, useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'

import { attachCatalogueIconAction, createCatalogueAction, saveCatalogueDetailsAction, saveCatalogueTranslationAction, setCatalogueArchivedAction } from '@/app/(admin)/admin/actions'
import type { CatalogueActionState, CatalogueKind } from '@/app/(admin)/admin/actions'
import { CatalogueRichTextEditor } from '@/components/admin/catalogue-rich-text-editor'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { emptyCatalogueDocument } from '@/lib/catalogue-document'
import { createClient } from '@/lib/supabase/client'
import type { Json } from '@/types/database.generated'

const locales = ['en', 'de', 'it', 'pt-BR', 'pt-PT'] as const
type Locale = (typeof locales)[number]
type Translation = { locale: Locale; slug: string; name: string; summary: string | null; content: Json; seoTitle: string | null; seoDescription: string | null; status: 'draft' | 'scheduled' | 'published' | 'archived'; scheduledFor: string | null; iconAltText: string | null }
type Option = { id: string; label: string }
type MediaOption = { id: string; label: string; path: string }
type Entry = { id: string; stableKey: string; displayOrder: number; isActive: boolean; iconMediaId: string | null; iconPath: string | null }
const initialActionState: CatalogueActionState = {}

export function CatalogueEditor({ kind, entry, translations = [], contacts, articles, media, selectedContactIds = [], selectedArticleIds = [] }: { kind: CatalogueKind; entry?: Entry; translations?: Translation[]; contacts: Option[]; articles: Option[]; media: MediaOption[]; selectedContactIds?: string[]; selectedArticleIds?: string[] }) {
	const router = useRouter()
	const [activeLocale, setActiveLocale] = useState<Locale>('en')
	const [contactIds, setContactIds] = useState(selectedContactIds)
	const [articleIds, setArticleIds] = useState(selectedArticleIds)
	const [createState, createAction, creating] = useActionState(createCatalogueAction, initialActionState)
	const [detailsState, detailsAction, savingDetails] = useActionState(saveCatalogueDetailsAction, initialActionState)
	const [archiveState, archiveAction, archiving] = useActionState(setCatalogueArchivedAction, initialActionState)
	const [uploadMessage, setUploadMessage] = useState<string | null>(null)
	const [uploading, setUploading] = useState(false)

	useEffect(() => { if (createState.entryId) router.push(`/admin/catalogue/${kind}/${createState.entryId}`) }, [createState.entryId, kind, router])

	async function uploadIcon(file: File, altText: string) {
		if (!entry) return
		setUploading(true); setUploadMessage(null)
		try {
			if (!['image/gif', 'image/jpeg', 'image/png', 'image/svg+xml', 'image/webp'].includes(file.type)) throw new Error('Choose a GIF, JPEG, PNG, SVG, or WebP icon.')
			if (file.size > 15 * 1024 * 1024) throw new Error('Icons must be 15 MiB or smaller.')
			if (altText.length < 3) throw new Error('Provide English alt text before uploading an icon.')
			const extension = file.name.split('.').pop()?.toLowerCase() || 'image'
			const path = `catalogue/${kind}/${entry.id}/${crypto.randomUUID()}.${extension}`
			const supabase = createClient()
			const { error } = await supabase.storage.from('public-media').upload(path, file, { cacheControl: '31536000', contentType: file.type, upsert: false })
			if (error) throw new Error(error.message)
			const dimensions = await imageDimensions(file)
			const result = await attachCatalogueIconAction({ kind, entryId: entry.id, objectPath: path, originalFilename: file.name, mimeType: file.type, fileSizeBytes: file.size, width: dimensions.width, height: dimensions.height, altText })
			if (result.error) throw new Error(result.error)
			setUploadMessage(result.success ?? 'Icon uploaded.'); router.refresh()
		} catch (error) { setUploadMessage(error instanceof Error ? error.message : 'Could not upload the icon.') } finally { setUploading(false) }
	}

	const sharedFields = <><input name="kind" type="hidden" value={kind} />{entry && <input name="entryId" type="hidden" value={entry.id} />}<input name="contactIds" type="hidden" value={JSON.stringify(contactIds)} /><input name="articleIds" type="hidden" value={JSON.stringify(articleIds)} /></>
	if (!entry) return <form action={createAction} className="mt-9 space-y-8"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="font-robo text-2xl text-slate-950">{singular(kind)} details</h2><p className="mt-1 text-sm text-slate-600">Set a stable identity, order, optional icon, team contacts, and articles. The catalogue remains data-only until the later public-template phase.</p><div className="mt-6 grid gap-5 md:grid-cols-2">{sharedFields}<Field label="Stable key"><Input autoFocus name="stableKey" placeholder="e.g. association-management" required /></Field><Field label="Display order"><Input defaultValue="0" min="0" name="displayOrder" type="number" /></Field><MediaSelect media={media} /><ContactPicker contacts={contacts} selectedIds={contactIds} setSelectedIds={setContactIds} /><ArticlePicker articles={articles} selectedIds={articleIds} setSelectedIds={setArticleIds} /></div></section><TranslationFields kind={kind} entryId={null} locale="en" translation={undefined} /><ActionNotice state={createState} /><div className="flex gap-3"><Button disabled={creating} type="submit">{creating && <LoaderCircle className="animate-spin" />}Create {singular(kind)}</Button><Button asChild type="button" variant="outline"><Link href="/admin/catalogue">Cancel</Link></Button></div></form>

	return <div className="space-y-8"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-robo text-2xl text-slate-950">Shared catalogue details</h2><p className="mt-1 text-sm text-slate-600">Canonical identity, placement, selected icon, team contacts, and article links are shared by all locales.</p></div><span className={entry.isActive ? 'rounded-full bg-emerald-50 px-3 py-1 text-sm font-medium text-emerald-700' : 'rounded-full bg-amber-50 px-3 py-1 text-sm font-medium text-amber-800'}>{entry.isActive ? 'Active' : 'Archived'}</span></div><form action={detailsAction} className="mt-6 grid gap-5 md:grid-cols-2">{sharedFields}<Field label="Stable key"><Input defaultValue={entry.stableKey} name="stableKey" required /></Field><Field label="Display order"><Input defaultValue={entry.displayOrder} min="0" name="displayOrder" type="number" /></Field><MediaSelect media={media} selectedId={entry.iconMediaId} /><ContactPicker contacts={contacts} selectedIds={contactIds} setSelectedIds={setContactIds} /><ArticlePicker articles={articles} selectedIds={articleIds} setSelectedIds={setArticleIds} /><div className="md:col-span-2"><Button disabled={savingDetails} type="submit">{savingDetails && <LoaderCircle className="animate-spin" />}Save shared details</Button></div></form><ActionNotice state={detailsState} /></section>
		<section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="font-robo text-2xl text-slate-950">Icon</h2><p className="mt-1 text-sm text-slate-600">Upload a replacement when it is not already in the media catalogue. Alternative text is authored independently in every locale below.</p><div className="mt-5 flex flex-wrap items-center gap-5">{entry.iconPath ? <Image alt="Current catalogue icon" className="size-20 rounded-lg border border-slate-200 object-contain p-1" height={80} src={createClient().storage.from('public-media').getPublicUrl(entry.iconPath).data.publicUrl} width={80} /> : <div className="flex size-20 items-center justify-center rounded-lg bg-slate-100 text-xs text-slate-500">No icon</div>}<div><Field label="English alt text for a new icon"><Input defaultValue={translations.find((item) => item.locale === 'en')?.iconAltText ?? ''} id="new-icon-alt" /></Field><label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-md bg-[#27335a] px-4 py-2 text-sm font-medium text-white hover:bg-[#1e294c]">{uploading ? <LoaderCircle className="size-4 animate-spin" /> : <ImagePlus className="size-4" />}{uploading ? 'Uploading…' : 'Upload replacement'}<input accept="image/gif,image/jpeg,image/png,image/svg+xml,image/webp" className="sr-only" disabled={uploading} onChange={(event) => { const file = event.target.files?.[0]; const alt = (document.getElementById('new-icon-alt') as HTMLInputElement | null)?.value.trim() ?? ''; if (file) void uploadIcon(file, alt) }} type="file" /></label>{uploadMessage && <p aria-live="polite" className="mt-2 text-sm text-slate-600">{uploadMessage}</p>}</div></div></section>
		<section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="font-robo text-2xl text-slate-950">Translations and publication</h2><p className="mt-1 text-sm text-slate-600">Each language has an independent name, URL, summary, controlled body, SEO, localized icon alt text, and publication state.</p><div className="mt-5 flex flex-wrap gap-2" role="tablist" aria-label={`${singular(kind)} translations`}>{locales.map((locale) => <Button aria-selected={activeLocale === locale} key={locale} onClick={() => setActiveLocale(locale)} role="tab" type="button" variant={activeLocale === locale ? 'default' : 'outline'}>{locale}</Button>)}</div><TranslationFields key={activeLocale} kind={kind} entryId={entry.id} locale={activeLocale} translation={translations.find((item) => item.locale === activeLocale)} /></section>
		<section className="flex flex-col justify-between gap-4 rounded-xl border border-amber-200 bg-amber-50 p-5 sm:flex-row sm:items-center"><div><h2 className="font-semibold text-amber-950">{entry.isActive ? `Archive this ${singular(kind)}` : `Restore this ${singular(kind)}`}</h2><p className="mt-1 text-sm text-amber-900">{entry.isActive ? 'Archiving hides all of its published translations while preserving content, contacts, and article links.' : 'Restoring makes already-published translations eligible for later public rendering again.'}</p></div><form action={archiveAction}><input name="kind" type="hidden" value={kind} /><input name="entryId" type="hidden" value={entry.id} /><input name="archive" type="hidden" value={entry.isActive ? 'true' : 'false'} /><Button disabled={archiving} type="submit" variant={entry.isActive ? 'destructive' : 'default'}>{entry.isActive ? 'Archive' : 'Restore'}</Button></form></section><ActionNotice state={archiveState} /></div>
}

function TranslationFields({ kind, entryId, locale, translation }: { kind: CatalogueKind; entryId: string | null; locale: Locale; translation?: Translation }) {
	const [state, action, pending] = useActionState(saveCatalogueTranslationAction, initialActionState)
	const suggestedSlug = translation?.slug ?? (locale === 'en' ? '' : '')
	const fields = <><input name="locale" type="hidden" value={locale} /><Field label="Localized name"><Input defaultValue={translation?.name ?? ''} name="name" required /></Field><Field label="Localized URL slug"><Input defaultValue={suggestedSlug} name="slug" placeholder="e.g. association-management" required /></Field><Field className="md:col-span-2" label="Landing summary"><textarea className="min-h-24 w-full rounded-md border border-input px-3 py-2 text-sm shadow-xs" defaultValue={translation?.summary ?? ''} maxLength={2000} name="summary" /></Field><div className="md:col-span-2"><span className="text-sm font-medium text-slate-700">Controlled rich-text content</span><p className="mt-1 text-sm text-slate-600">Use only headings, paragraphs, emphasis, links, lists, and quotations. Layout stays in code.</p><CatalogueRichTextEditor initialValue={translation?.content ?? emptyCatalogueDocument()} /></div><Field label="Localized icon alt text"><Input defaultValue={translation?.iconAltText ?? ''} name="iconAltText" placeholder={`Describe the ${singular(kind)} icon`} /></Field><Field label="Publication status"><select className="h-9 w-full rounded-md border border-input bg-white px-3 text-sm" defaultValue={translation?.status ?? 'draft'} name="status"><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option><option value="archived">Archived</option></select></Field><Field label="Scheduled publication time"><Input defaultValue={toDateTimeLocal(translation?.scheduledFor)} name="scheduledFor" type="datetime-local" /></Field><div aria-hidden="true" /><Field label="SEO title"><Input defaultValue={translation?.seoTitle ?? ''} maxLength={160} name="seoTitle" /></Field><Field label="SEO description"><textarea className="min-h-20 w-full rounded-md border border-input px-3 py-2 text-sm shadow-xs" defaultValue={translation?.seoDescription ?? ''} maxLength={320} name="seoDescription" /></Field></>
	if (!entryId) return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="font-robo text-2xl text-slate-950">English content</h2><p className="mt-1 text-sm text-slate-600">Create the first complete localized record now. Other languages can be managed after this save.</p><div className="mt-6 grid gap-5 md:grid-cols-2">{fields}</div></section>
	return <form action={action} className="mt-6 grid gap-5 md:grid-cols-2"><input name="kind" type="hidden" value={kind} /><input name="entryId" type="hidden" value={entryId} />{fields}<div className="md:col-span-2"><Button disabled={pending} type="submit">{pending && <LoaderCircle className="animate-spin" />}Save {locale} translation</Button></div><ActionNotice state={state} /></form>
}

function MediaSelect({ media, selectedId }: { media: MediaOption[]; selectedId?: string | null }) { return <Field label="Selected icon from media"><select className="h-9 w-full rounded-md border border-input bg-white px-3 text-sm" defaultValue={selectedId ?? ''} name="iconMediaId"><option value="">No icon selected</option>{media.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><span className="text-xs font-normal text-slate-500">Upload a new icon after saving if it is not listed.</span></Field> }
function ContactPicker({ contacts, selectedIds, setSelectedIds }: { contacts: Option[]; selectedIds: string[]; setSelectedIds: (ids: string[]) => void }) { const selected = useMemo(() => selectedIds.map((id) => contacts.find((item) => item.id === id)).filter((item): item is Option => Boolean(item)), [contacts, selectedIds]); function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= selectedIds.length) return; const next = [...selectedIds]; [next[index], next[target]] = [next[target], next[index]]; setSelectedIds(next) } return <div className="md:col-span-2 rounded-lg border border-slate-200 p-4"><h3 className="font-semibold text-slate-900">Ordered team contacts</h3><p className="mt-1 text-sm text-slate-600">Only active team members can be contacts. The first selected person is displayed first.</p><select className="mt-3 h-9 w-full rounded-md border border-input bg-white px-3 text-sm" onChange={(event) => { if (event.target.value && !selectedIds.includes(event.target.value)) setSelectedIds([...selectedIds, event.target.value]); event.target.value = '' }} value=""><option value="">Add a team contact…</option>{contacts.filter((item) => !selectedIds.includes(item.id)).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><div className="mt-3 space-y-2">{selected.map((item, index) => <div className="flex items-center justify-between rounded-md bg-slate-50 px-3 py-2 text-sm" key={item.id}><span>{index + 1}. {item.label}</span><span className="flex gap-1"><Button aria-label={`Move ${item.label} up`} disabled={index === 0} onClick={() => move(index, -1)} size="icon" type="button" variant="ghost"><ArrowUp /></Button><Button aria-label={`Move ${item.label} down`} disabled={index === selected.length - 1} onClick={() => move(index, 1)} size="icon" type="button" variant="ghost"><ArrowDown /></Button><Button onClick={() => setSelectedIds(selectedIds.filter((id) => id !== item.id))} type="button" variant="ghost">Remove</Button></span></div>)}{!selected.length && <p className="text-sm text-slate-500">No contacts selected.</p>}</div></div> }
function ArticlePicker({ articles, selectedIds, setSelectedIds }: { articles: Option[]; selectedIds: string[]; setSelectedIds: (ids: string[]) => void }) { return <div className="md:col-span-2 rounded-lg border border-slate-200 p-4"><h3 className="font-semibold text-slate-900">Related articles</h3><p className="mt-1 text-sm text-slate-600">This uses the existing article taxonomy relations. The schema does not define a separate ordered service/sector article relation.</p><select className="mt-3 h-9 w-full rounded-md border border-input bg-white px-3 text-sm" onChange={(event) => { if (event.target.value && !selectedIds.includes(event.target.value)) setSelectedIds([...selectedIds, event.target.value]); event.target.value = '' }} value=""><option value="">Link an article…</option>{articles.filter((item) => !selectedIds.includes(item.id)).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><div className="mt-3 flex flex-wrap gap-2">{selectedIds.map((id) => { const article = articles.find((item) => item.id === id); return <span className="inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1 text-sm" key={id}>{article?.label ?? 'Unavailable article'}<button aria-label={`Remove ${article?.label ?? 'article'}`} onClick={() => setSelectedIds(selectedIds.filter((item) => item !== id))} type="button">×</button></span> })}{!selectedIds.length && <p className="text-sm text-slate-500">No related articles selected.</p>}</div></div> }
function Field({ label, children, className }: { label: string; children: React.ReactNode; className?: string }) { return <label className={`grid gap-1.5 text-sm font-medium text-slate-700 ${className ?? ''}`}><span>{label}</span>{children}</label> }
function ActionNotice({ state }: { state: CatalogueActionState }) { return state.error ? <p aria-live="polite" className="md:col-span-2 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-800">{state.error}</p> : state.success ? <p aria-live="polite" className="md:col-span-2 rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-800">{state.success}</p> : null }
function singular(kind: CatalogueKind | 'services') { return kind === 'services' ? 'service' : 'sector' }
function toDateTimeLocal(value: string | null | undefined) { return value ? new Date(value).toISOString().slice(0, 16) : '' }
async function imageDimensions(file: File): Promise<{ width: number | null; height: number | null }> { if (file.type === 'image/svg+xml') return { width: null, height: null }; const url = URL.createObjectURL(file); try { const image = new globalThis.Image(); await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error('The selected image could not be read.')); image.src = url }); return { width: image.naturalWidth || null, height: image.naturalHeight || null } } finally { URL.revokeObjectURL(url) } }
