'use client'

import { LoaderCircle } from 'lucide-react'
import { useActionState, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

import { createOfficeAction, createRegionAction, saveOfficeDetailsAction, saveOfficeTranslationAction, saveRegionDetailsAction, saveRegionTranslationAction, setOfficeArchivedAction, setRegionArchivedAction } from '@/app/(admin)/admin/actions'
import type { OutreachActionState } from '@/app/(admin)/admin/actions'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import type { Json } from '@/types/database.generated'

const locales = ['en', 'de', 'it', 'pt-BR', 'pt-PT'] as const
type Locale = (typeof locales)[number]
const initialState: OutreachActionState = {}
type Translation = { locale: Locale; slug?: string; name: string; city?: string | null; address?: string | null; status: 'draft' | 'scheduled' | 'published' | 'archived'; scheduledFor: string | null }

function map(config: Json) { const value = config && typeof config === 'object' && !Array.isArray(config) ? config as Record<string, unknown> : {}; const coordinates = Array.isArray(value.coordinates) ? value.coordinates : []; return { longitude: typeof coordinates[0] === 'number' ? String(coordinates[0]) : '', latitude: typeof coordinates[1] === 'number' ? String(coordinates[1]) : '', zoom: typeof value.zoom === 'number' ? String(value.zoom) : '' } }

export function RegionEditor({ region, translations = [] }: { region?: { id: string; stableKey: string; displayOrder: number; isActive: boolean; mapConfig: Json }; translations?: Translation[] }) {
	const router = useRouter(); const [locale, setLocale] = useState<Locale>('en'); const [createState, createAction, creating] = useActionState(createRegionAction, initialState); const [detailsState, detailsAction, saving] = useActionState(saveRegionDetailsAction, initialState); const [archiveState, archiveAction, archiving] = useActionState(setRegionArchivedAction, initialState)
	useEffect(() => { if (createState.entryId) router.push(`/admin/outreach/regions/${createState.entryId}`) }, [createState.entryId, router]); const values = map(region?.mapConfig ?? {})
	if (!region) return <form action={createAction} className="mt-8 grid gap-4 rounded-xl border border-slate-200 bg-white p-5 md:grid-cols-2"><p className="md:col-span-2 text-sm text-slate-600">New regions start with English content. The optional map focus is restricted to the legacy coordinates and zoom shape.</p><SharedRegionFields values={values} /><NewRegionTranslationFields /><Notice state={createState} /><div className="md:col-span-2"><Button disabled={creating} type="submit">{creating && <LoaderCircle className="animate-spin" />}Create region</Button></div></form>
	return <div className="mt-8 space-y-7"><form action={detailsAction} className="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 md:grid-cols-2"><input name="regionId" type="hidden" value={region.id} /><SharedRegionFields region={region} values={values} /><Notice state={detailsState} /><div className="md:col-span-2 flex flex-wrap gap-2"><Button disabled={saving} type="submit">{saving && <LoaderCircle className="animate-spin" />}Save shared details</Button><Button disabled={archiving} formAction={archiveAction} name="archive" type="submit" value={String(region.isActive)} variant="outline">{region.isActive ? 'Archive region' : 'Restore region'}</Button></div><Notice state={archiveState} /></form><section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap gap-2">{locales.map((item) => <Button key={item} onClick={() => setLocale(item)} type="button" variant={locale === item ? 'default' : 'outline'}>{item}</Button>)}</div><RegionTranslationForm regionId={region.id} locale={locale} translation={translations.find((item) => item.locale === locale)} /></section></div>
}
function SharedRegionFields({ region, values }: { region?: { stableKey: string; displayOrder: number }; values: { longitude: string; latitude: string; zoom: string } }) { return <><Field label="Stable key"><Input defaultValue={region?.stableKey ?? ''} name="stableKey" required /></Field><Field label="Display order"><Input defaultValue={region?.displayOrder ?? 0} min="0" name="displayOrder" type="number" required /></Field><Field label="Map longitude"><Input defaultValue={values.longitude} name="mapLongitude" step="any" type="number" /></Field><Field label="Map latitude"><Input defaultValue={values.latitude} name="mapLatitude" step="any" type="number" /></Field><Field label="Map zoom"><Input defaultValue={values.zoom} name="mapZoom" step="any" type="number" /></Field></> }
function RegionTranslationForm({ regionId, locale, translation }: { regionId: string; locale: Locale; translation?: Translation }) { const [state, action, pending] = useActionState(saveRegionTranslationAction, initialState); return <form action={action} className="mt-5 grid gap-4 md:grid-cols-2"><input name="regionId" type="hidden" value={regionId} /><input name="locale" type="hidden" value={locale} /><Field label="Name"><Input defaultValue={translation?.name ?? ''} name="name" required /></Field><Field label="URL slug"><Input defaultValue={translation?.slug ?? ''} name="slug" required /></Field><Field label="Publication"><select className="input-select" defaultValue={translation?.status ?? 'draft'} name="status"><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option><option value="archived">Archived</option></select></Field><Field label="Scheduled publication"><Input defaultValue={dateTime(translation?.scheduledFor)} name="scheduledFor" type="datetime-local" /></Field><div className="md:col-span-2"><Button disabled={pending} type="submit">{pending && <LoaderCircle className="animate-spin" />}Save {locale} translation</Button></div><Notice state={state} /></form> }
function NewRegionTranslationFields() { return <><input name="locale" type="hidden" value="en" /><Field label="Name"><Input name="name" required /></Field><Field label="URL slug"><Input name="slug" required /></Field><Field label="Publication"><select className="input-select" name="status"><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option></select></Field><Field label="Scheduled publication"><Input name="scheduledFor" type="datetime-local" /></Field></> }

export function OfficeEditor({ office, countries, translations = [] }: { office?: { id: string; stableKey: string; countryCode: string | null; email: string | null; phone: string | null; latitude: number | null; longitude: number | null; displayOrder: number; isActive: boolean }; countries: { code: string; label: string }[]; translations?: Translation[] }) {
	const router = useRouter(); const [locale, setLocale] = useState<Locale>('en'); const [createState, createAction, creating] = useActionState(createOfficeAction, initialState); const [detailsState, detailsAction, saving] = useActionState(saveOfficeDetailsAction, initialState); const [archiveState, archiveAction, archiving] = useActionState(setOfficeArchivedAction, initialState)
	useEffect(() => { if (createState.entryId) router.push(`/admin/outreach/offices/${createState.entryId}`) }, [createState.entryId, router])
	if (!office) return <form action={createAction} className="mt-8 grid gap-4 rounded-xl border border-slate-200 bg-white p-5 md:grid-cols-2"><OfficeFields countries={countries} /><OfficeTranslationFields locale="en" /><Notice state={createState} /><div className="md:col-span-2"><Button disabled={creating} type="submit">{creating && <LoaderCircle className="animate-spin" />}Create office</Button></div></form>
	return <div className="mt-8 space-y-7"><form action={detailsAction} className="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 md:grid-cols-2"><input name="officeId" type="hidden" value={office.id} /><OfficeFields countries={countries} office={office} /><Notice state={detailsState} /><div className="md:col-span-2 flex flex-wrap gap-2"><Button disabled={saving} type="submit">{saving && <LoaderCircle className="animate-spin" />}Save shared details</Button><Button disabled={archiving} formAction={archiveAction} name="archive" type="submit" value={String(office.isActive)} variant="outline">{office.isActive ? 'Archive office' : 'Restore office'}</Button></div><Notice state={archiveState} /></form><section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap gap-2">{locales.map((item) => <Button key={item} onClick={() => setLocale(item)} type="button" variant={locale === item ? 'default' : 'outline'}>{item}</Button>)}</div><OfficeTranslationForm locale={locale} officeId={office.id} translation={translations.find((item) => item.locale === locale)} /></section></div>
}
function OfficeFields({ office, countries }: { office?: { stableKey: string; countryCode: string | null; email: string | null; phone: string | null; latitude: number | null; longitude: number | null; displayOrder: number }; countries: { code: string; label: string }[] }) { return <><Field label="Stable key"><Input defaultValue={office?.stableKey ?? ''} name="stableKey" required /></Field><Field label="Primary country"><select className="input-select" defaultValue={office?.countryCode ?? ''} name="countryCode"><option value="">No primary country</option>{countries.map((country) => <option key={country.code} value={country.code}>{country.label} ({country.code})</option>)}</select></Field><Field label="Email"><Input defaultValue={office?.email ?? ''} name="email" type="email" /></Field><Field label="Phone"><Input defaultValue={office?.phone ?? ''} name="phone" /></Field><Field label="Latitude"><Input defaultValue={office?.latitude ?? ''} name="latitude" step="any" type="number" /></Field><Field label="Longitude"><Input defaultValue={office?.longitude ?? ''} name="longitude" step="any" type="number" /></Field><Field label="Display order"><Input defaultValue={office?.displayOrder ?? 0} min="0" name="displayOrder" type="number" required /></Field></> }
function OfficeTranslationFields({ locale, translation }: { locale: string; translation?: Translation }) { return <><input name="locale" type="hidden" value={locale} /><Field label="Office name"><Input defaultValue={translation?.name ?? ''} name="name" required /></Field><Field label="City"><Input defaultValue={translation?.city ?? ''} name="city" /></Field><Field className="md:col-span-2" label="Address"><textarea className="input-textarea" defaultValue={translation?.address ?? ''} name="address" rows={3} /></Field><Field label="Publication"><select className="input-select" defaultValue={translation?.status ?? 'draft'} name="status"><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option><option value="archived">Archived</option></select></Field><Field label="Scheduled publication"><Input defaultValue={dateTime(translation?.scheduledFor)} name="scheduledFor" type="datetime-local" /></Field></> }
function OfficeTranslationForm({ officeId, locale, translation }: { officeId: string; locale: Locale; translation?: Translation }) { const [state, action, pending] = useActionState(saveOfficeTranslationAction, initialState); return <form action={action} className="mt-5 grid gap-4 md:grid-cols-2"><input name="officeId" type="hidden" value={officeId} /><OfficeTranslationFields locale={locale} translation={translation} /><div className="md:col-span-2"><Button disabled={pending} type="submit">{pending && <LoaderCircle className="animate-spin" />}Save {locale} office content</Button></div><Notice state={state} /></form> }
function Field({ label, children, className }: { label: string; children: React.ReactNode; className?: string }) { return <label className={`grid gap-1.5 text-sm font-medium text-slate-700 ${className ?? ''}`}><span>{label}</span>{children}</label> }
function Notice({ state }: { state: OutreachActionState }) { return state.error ? <p aria-live="polite" className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-800">{state.error}</p> : state.success ? <p aria-live="polite" className="rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-800">{state.success}</p> : null }
function dateTime(value: string | null | undefined) { return value ? new Date(value).toISOString().slice(0, 16) : '' }
