'use client'

import { LoaderCircle, PencilLine, Plus } from 'lucide-react'
import { useActionState, useMemo, useState } from 'react'

import { createRedirectAction, setRedirectEnabledAction, updateRedirectAction } from '@/app/(admin)/admin/redirects/actions'
import type { RedirectActionState } from '@/app/(admin)/admin/redirects/actions'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

type RedirectRow = { id: string; locale: string | null; sourcePath: string; destinationPath: string; statusCode: number; isActive: boolean; updatedAt: string }
const initial: RedirectActionState = {}

export function RedirectRegistry({ redirects }: { redirects: RedirectRow[] }) {
	const [query, setQuery] = useState(''); const [showCreate, setShowCreate] = useState(false)
	const visible = useMemo(() => redirects.filter((item) => `${item.locale ?? 'global'} ${item.sourcePath} ${item.destinationPath}`.toLowerCase().includes(query.trim().toLowerCase())), [query, redirects])
	return <div className="mt-9 space-y-6"><div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-950"><strong>Registry only:</strong> enabled records are prepared for review, but the application does not currently execute this registry. Public redirect handling remains deferred until the localized route strategy is implemented.</div><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><Input className="max-w-md bg-white" onChange={(event) => setQuery(event.target.value)} placeholder="Search source, destination or locale" value={query} /><Button onClick={() => setShowCreate((value) => !value)} type="button"><Plus />New redirect</Button></div>{showCreate && <CreateRedirectForm /> }<div className="space-y-4">{visible.map((redirect) => <RedirectEditor key={redirect.id} redirect={redirect} />)}{!visible.length && <div className="rounded-xl border border-slate-200 bg-white px-5 py-14 text-center text-sm text-slate-500">No redirects match this view.</div>}</div></div>
}

function CreateRedirectForm() { const [state, action, pending] = useActionState(createRedirectAction, initial); return <form action={action} className="rounded-xl border border-blue-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Plus className="size-4" /><h2 className="font-semibold">Create permanent redirect</h2></div><p className="mt-1 text-sm text-slate-600">New records are disabled unless explicitly enabled below.</p><div className="mt-5 grid gap-4 md:grid-cols-[9rem_1fr_1fr_7rem]"><LocaleSelect /><Field label="Legacy source path"><Input name="sourcePath" placeholder="/old-path" required /></Field><Field label="Destination"><Input name="destinationPath" placeholder="/new-path or https://…" required /></Field><StatusSelect /></div><label className="mt-4 flex items-center gap-2 text-sm text-slate-700"><input name="enabled" type="checkbox" />Enable in registry after validation</label><div className="mt-5"><Button disabled={pending} type="submit">{pending && <LoaderCircle className="animate-spin" />}Create redirect</Button></div><Notice state={state} /></form> }

function RedirectEditor({ redirect }: { redirect: RedirectRow }) { const [editing, setEditing] = useState(false); const [editState, editAction, saving] = useActionState(updateRedirectAction, initial); const [toggleState, toggleAction, toggling] = useActionState(setRedirectEnabledAction, initial); return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{redirect.locale ?? 'global'}</Badge><Badge className={redirect.isActive ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-slate-200 bg-slate-50 text-slate-600'} variant="outline">{redirect.isActive ? 'Enabled' : 'Disabled'}</Badge><span className="text-xs text-slate-500">HTTP {redirect.statusCode}</span></div><p className="mt-3 break-all font-medium text-slate-900">{redirect.sourcePath}</p><p className="mt-1 break-all text-sm text-slate-600">→ {redirect.destinationPath}</p><p className="mt-2 text-xs text-slate-400">Updated {new Date(redirect.updatedAt).toLocaleString()}</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => setEditing((value) => !value)} type="button" variant="outline"><PencilLine />Edit</Button><form action={toggleAction}><input name="id" type="hidden" value={redirect.id} /><input name="enabled" type="hidden" value={String(!redirect.isActive)} /><Button disabled={toggling} type="submit" variant={redirect.isActive ? 'destructive' : 'default'}>{redirect.isActive ? 'Disable' : 'Enable'}</Button></form></div></div><Notice state={toggleState} />{editing && <form action={editAction} className="mt-5 border-t border-slate-200 pt-5"><input name="id" type="hidden" value={redirect.id} /><div className="grid gap-4 md:grid-cols-[9rem_1fr_1fr_7rem]"><LocaleSelect locale={redirect.locale} /><Field label="Legacy source path"><Input defaultValue={redirect.sourcePath} name="sourcePath" required /></Field><Field label="Destination"><Input defaultValue={redirect.destinationPath} name="destinationPath" required /></Field><StatusSelect statusCode={redirect.statusCode} /></div><div className="mt-5"><Button disabled={saving} type="submit">{saving && <LoaderCircle className="animate-spin" />}Save redirect</Button></div><Notice state={editState} /></form>}</section> }

function LocaleSelect({ locale }: { locale?: string | null }) { return <Field label="Locale scope"><select className="input-select" defaultValue={locale ?? ''} name="locale"><option value="">Global</option>{['en', 'de', 'it', 'pt-BR', 'pt-PT'].map((item) => <option key={item} value={item}>{item}</option>)}</select></Field> }
function StatusSelect({ statusCode = 308 }: { statusCode?: number }) { return <Field label="Permanent code"><select className="input-select" defaultValue={statusCode} name="statusCode"><option value="308">308</option><option value="301">301</option></select></Field> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium text-slate-700"><span>{label}</span>{children}</label> }
function Notice({ state }: { state: RedirectActionState }) { return state.error ? <p className="mt-4 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-800" role="alert">{state.error}</p> : state.success ? <p className="mt-4 rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-800" role="status">{state.success}</p> : null }
