import Link from 'next/link'
import { notFound } from 'next/navigation'

import { CountryEditor } from '@/components/admin/country-editor'
import { createClient } from '@/lib/supabase/server'
import type { Json } from '@/types/database.generated'

export default async function CountryPage({ params }: { params: Promise<{ code: string }> }) {
	const { code } = await params; if (!/^[A-Za-z]{2}$/.test(code)) notFound(); const countryCode = code.toUpperCase(); const supabase = await createClient()
	const [{ data: country, error: countryError }, { data: translations, error: translationError }, { data: regions, error: regionError }, { data: regionTranslations, error: regionTranslationError }, { data: services, error: serviceError }, { data: serviceTranslations, error: serviceTranslationError }, { data: people, error: peopleError }, { data: offices, error: officeError }, { data: media, error: mediaError }, { data: assignments, error: assignmentError }, { data: experts, error: expertError }, { data: countryOffices, error: countryOfficeError }, { data: statistics, error: statisticError }, { data: serviceCopies, error: copyError }] = await Promise.all([
		supabase.from('countries').select('code, region_id, is_covered, display_order, last_reviewed_on, flag_media_id, outline_media_id, map_config').eq('code', countryCode).maybeSingle(), supabase.from('country_translations').select('locale, slug, name, summary, coverage_summary, content, seo_title, seo_description, status, scheduled_for').eq('country_code', countryCode), supabase.from('regions').select('id, stable_key').eq('is_active', true).order('display_order'), supabase.from('region_translations').select('region_id, name').eq('locale', 'en'), supabase.from('services').select('id, stable_key').eq('is_active', true).order('display_order'), supabase.from('service_translations').select('service_id, name').eq('locale', 'en'), supabase.from('people').select('id, display_name').eq('is_active', true).order('display_name'), supabase.from('offices').select('id, stable_key').eq('is_active', true).order('display_order'), supabase.from('media_assets').select('id, original_filename').order('created_at', { ascending: false }).limit(200), supabase.from('country_services').select('service_id, coverage_level').eq('country_code', countryCode).order('display_order'), supabase.from('country_people').select('person_id').eq('country_code', countryCode).eq('relationship', 'expert').order('display_order'), supabase.from('country_offices').select('office_id').eq('country_code', countryCode).order('display_order'), supabase.from('country_statistics').select('id, metric_key, numeric_value, unit, statistic_year, source_url, display_order').eq('country_code', countryCode).order('display_order'), supabase.from('country_service_translations').select('service_id, locale, summary, content').eq('country_code', countryCode),
	])
	if (countryError || translationError || regionError || regionTranslationError || serviceError || serviceTranslationError || peopleError || officeError || mediaError || assignmentError || expertError || countryOfficeError || statisticError || copyError) throw new Error(`Unable to load country: ${countryError?.message ?? translationError?.message ?? regionError?.message ?? regionTranslationError?.message ?? serviceError?.message ?? serviceTranslationError?.message ?? peopleError?.message ?? officeError?.message ?? mediaError?.message ?? assignmentError?.message ?? expertError?.message ?? countryOfficeError?.message ?? statisticError?.message ?? copyError?.message}`)
	if (!country) notFound()
	const { data: mediaAlts, error: altError } = await supabase.from('media_asset_translations').select('media_asset_id, locale, alt_text').in('media_asset_id', [country.flag_media_id, country.outline_media_id].filter((id): id is string => Boolean(id)))
	if (altError) throw new Error(`Unable to load country media alt text: ${altError.message}`)
	const statisticIds = (statistics ?? []).map((statistic) => statistic.id)
	const { data: statisticLabels, error: labelError } = statisticIds.length ? await supabase.from('country_statistic_translations').select('statistic_id, locale, label, display_value').in('statistic_id', statisticIds) : { data: [], error: null }
	if (labelError) throw new Error(`Unable to load country statistic labels: ${labelError.message}`)
	return <div className="mx-auto max-w-5xl"><Link className="text-sm font-semibold text-[#53617f] underline-offset-4 hover:underline" href="/admin/outreach">← Our Outreach</Link><p className="mt-5 text-xs font-semibold uppercase tracking-[0.2em] text-[#53617f]">Our Outreach administration</p><h1 className="mt-2 font-robo text-4xl tracking-tight text-slate-950">{(translations ?? []).find((item) => item.locale === 'en')?.name ?? country.code}</h1><CountryEditor country={{ code: country.code, regionId: country.region_id, isCovered: country.is_covered, displayOrder: country.display_order, lastReviewedOn: country.last_reviewed_on, flagMediaId: country.flag_media_id, outlineMediaId: country.outline_media_id, mapConfig: country.map_config as Json }} experts={(experts ?? []).map((item) => item.person_id)} countryOffices={(countryOffices ?? []).map((item) => item.office_id)} media={(media ?? []).map((item) => ({ id: item.id, label: item.original_filename ?? item.id }))} offices={(offices ?? []).map((item) => ({ id: item.id, label: item.stable_key }))} people={(people ?? []).map((item) => ({ id: item.id, label: item.display_name }))} regions={(regions ?? []).map((item) => ({ id: item.id, label: (regionTranslations ?? []).find((translation) => translation.region_id === item.id)?.name ?? item.stable_key }))} serviceAssignments={(assignments ?? []).map((item) => ({ serviceId: item.service_id, coverageLevel: item.coverage_level }))} serviceCopies={(serviceCopies ?? []).map((item) => ({ serviceId: item.service_id, locale: item.locale, summary: item.summary, content: item.content as Json }))} services={(services ?? []).map((item) => ({ id: item.id, label: (serviceTranslations ?? []).find((translation) => translation.service_id === item.id)?.name ?? item.stable_key }))} statisticLabels={(statisticLabels ?? []).map((item) => ({ statisticId: item.statistic_id, locale: item.locale, label: item.label, displayValue: item.display_value }))} statistics={(statistics ?? []).map((item) => ({ id: item.id, metricKey: item.metric_key, numericValue: item.numeric_value === null ? null : Number(item.numeric_value), unit: item.unit, statisticYear: item.statistic_year, sourceUrl: item.source_url, displayOrder: item.display_order }))} translations={(translations ?? []).map((item) => ({ locale: item.locale as 'en' | 'de' | 'it' | 'pt-BR' | 'pt-PT', slug: item.slug, name: item.name, summary: item.summary, coverageSummary: item.coverage_summary, content: item.content as Json, seoTitle: item.seo_title, seoDescription: item.seo_description, status: item.status, scheduledFor: item.scheduled_for, flagAltText: (mediaAlts ?? []).find((alt) => alt.media_asset_id === country.flag_media_id && alt.locale === item.locale)?.alt_text ?? null, outlineAltText: (mediaAlts ?? []).find((alt) => alt.media_asset_id === country.outline_media_id && alt.locale === item.locale)?.alt_text ?? null }))} /></div>
}
